# Generated by Django 4.1.7 on 2023-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.CharField(default='transferir.png', max_length=500),
        ),
    ]
