# Generated by Django 4.1.7 on 2023-03-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_alter_aluno_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='imagem',
            new_name='image',
        ),
    ]
